### ISSUE TITLE
大佬，怎么只把取消自动下载地图添加到文件里

### ISSUE THREAD

**Issue by 1843971460** [liesauer/HumanMod#11]
大佬，怎么只把取消自动下载地图添加到文件里

**Comment by liesauer** [comment]
关键代码在这，把`LoadLevel`换成`GetLevel`，这样子就取消自动下载了。
https://github.com/liesauer/HumanMod/blob/b1014774bfc0df09f095d1a06f990a6877062df3/patched/Assembly-CSharp/16.LevelInformationBox.GetNewLevel.cs#L244-L251

**Comment by 1843971460** [comment]
谢谢
