### ISSUE TITLE
编译方案可以不使用dnSpy进行注入，使用人类源码直接编译到Assembly-CSharp或者交叉编译

### ISSUE THREAD

**Issue by XiaoHuiHui233** [liesauer/HumanMod#22]
人类一败涂地的游戏源码（Assembly-CSharp.dll）反编译工作持续稳定的进行中，可参照：
https://github.com/XiaoHuiHui233/HumanFallFlat

基于此，使用dnSpy注入的方式显得并没有那么高效，更推荐的做法有如下两种：
1、将MOD代码融合到Assembly-CSharp中进行编译，直接得到新的游戏文件。
此种方式较为简单，快捷，代码内嵌程度较深，方便二次开发和后续开发，但是对于诸如全局开关的设计实现起来较为困难。
2、使用原版代码、MOD扩充代码、MOD修改代码两两交叉编译的方式进行编译。
此种方式编译次数较多，较为繁琐，需要理清依赖结构，并且对修改原版代码的函数列表不友好，但可以独立出MOD代码，便于全局开关等设计的开发。

**Comment by liesauer** [comment]
你提到非常好的一个点，在一开始开发，采用人工补丁的方式显得更加方便（改动少），自由度更高（按需改动），不需要为了一丢丢东西就将整个涉及到的类反编译，但随着后面功能、改动的添多，这样子的补丁方式愈显得低效，现在的代码已经改成类似于你说的那种方式，从1.3.1开始，即感染者版本，对需要改动的地方反编译整个类并修改，编译后再将代码合并至原程序集中，不过这样的改动也造成现在项目卡住，因为还没有办法将代码合并到原程序集中，所以感染者模式才一直拖着，如果有可行的方案可联系我，非常感谢！！！

后面基础功能逐步完善后，整个HumanMod将会拆分为3个项目，HumanMod将正式成为Mod框架，现在的HumanMod则成为框架的一个官方Mod，至于名字以后再定：
1. patched-Assembly、patched-Assembly-firstpass
对人类的代码进行部分反编译，以配合HumanMod框架的基础功能进行封装开发。

2. HumanMod框架
提供一些基础的功能，以便Mod作者在HumanMod框架的基础上开发Mod。

3. HumanMod（以后可能会改名）
即将现有的功能单独成一个Mod项目。

**Comment by XiaoHuiHui233** [comment]
我目前在做通用MOD框架的开发，所以我这里首要解决的问题就是反编译整体源代码并且重新编译测试通过。
我做过很多测试，都是依赖我上面提到的github项目里的源码，这份源码我会随着人类的版本更新同步更新的。
这份源码是使用ILSpy反编译器（不同于dnSpy，后者经测试存在大量语法冲突问题）进行反编译，去除掉无法通过编译的注解和语法糖。之后测试了重新编译并替换游戏文件，游戏可以正常启动。
起初使用ILSpy进行反编译主要是因为我本地的环境是macOS，不能使用dnSpy。
因此我的思路就是通过跨平台的开源.net反编译工具反编译人类游戏的源码，然后使用mono虚拟机带的csc程序重新编译，从而实现注入游戏文件。
在我重新回到Win平台之后我便继续着手于使用ILSpy反编译生成csharp项目，导入Visual Studio并通过VS的.net framework编译器进行编译。经过我的测试，此方法在.net framework 3.5下可行，并且编译生成的文件替换源文件游戏不会发生任何形式的崩溃。
之后我尝试自己添加了很多功能类进行各种我的开发过程的测试，它们均通过了编译，且在游戏中运行正常。
因此我十分确信基于我项目的代码（或者重新通过ILSpy反编译，去除少量报错代码）添加更多的功能是可以完美的在.net framework 3.5环境下重新编译并正确运行的。

**Comment by liesauer** [comment]
我最初也尝试过用dnSpy反编译整个游戏，好像3000+的errors还是多少来着，当时还是凌晨，不知道是不是眼花替换错代码了（因为很多错误都是类似的，所以我是先用全局替换把相同的大部分错误消掉），消掉errors后进游戏崩溃，我吐了，才改成现在的反编译局部代码。
那这样子我们估计可以有合作机会，我可以引用你的人类源代码，并以此基础上进行二次开发。

**Comment by XiaoHuiHui233** [comment]
有微信或者qq嘛 用issue联系不太方便XD

**Comment by XiaoHuiHui233** [comment]
有微信或者qq嘛 用issue联系不太方便XD

**Comment by liesauer** [comment]
qq12268668052020年10月3日 20:41，小灰灰 <notifications@github.com>写道：

有微信或者qq嘛 用issue联系不太方便XD
